//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChristianHymnsCCLISongNumber.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChristianHymnsCCLISongNumber.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	The Worship of God	Praise and thanksgiving	William Kethe d. 1594	L.M.
        ///2	Before Jehovah&apos;s Awesome Throne	Psalm 1	Isaac Watts 1674-1748; altd. by John Wesley 1703-91;	L.M.
        ///3	&quot;Angel Voices, Ever Singing&quot;	Psalm 1	Francis Pott 1832-1909	8 5. 8 5. 8 4 3
        ///4	Christ Is Our Corner-Stone		&quot;Latin, 6th or 7th cent.;&lt;br&gt;tr. by John Chandler 1806-76&quot;	6 6. 6 6. 4 4. 4 4
        ///5	At all times I will bless the Lord	 Psalm 34:1-10	SING PSALMS 2003	D.C.M.
        ///6	Come all you nations everywhere	PSALM 117	&quot;Graham D S Deans, b. 1953&quot;	L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SongList {
            get {
                return ResourceManager.GetString("SongList", resourceCulture);
            }
        }
    }
}
